name: Deploy Frontend RJ Improves

on:
  push:
    branches:
      - main # Verifica si tu rama es 'main' o 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Entrar al directorio del código en el VPS
            cd ~/sge-bitecso-front
            
            # 2. Actualizar el repositorio con los últimos cambios
            git reset --hard origin/main
            git pull origin main
            
            # 3. Instalar dependencias y generar el build de producción
            npm install
            npm run build -- --configuration=production
            
            # 4. Limpiar la carpeta de destino de Nginx
            sudo rm -rf /var/www/rjimproves/front/*
            
            # 5. Mover el contenido de 'browser' a la raíz (Solución al 403)
            # Angular 17+ guarda el index.html dentro de /browser/
            sudo cp -r ~/sge-bitecso-front/dist/sge-bitecso-front/browser/* /var/www/rjimproves/front/
            
            # 6. Corregir permisos de archivos y carpetas
            # Asignamos al usuario de Nginx (www-data) y damos permisos de lectura
            sudo chown -R www-data:www-data /var/www/rjimproves/front
            sudo chmod -R 755 /var/www/rjimproves/front
            
            # 7. Asegurar permisos de ejecución en las carpetas superiores
            sudo chmod +x /var/www
            sudo chmod +x /var/www/rjimproves
            
            # 8. Reiniciar Nginx para aplicar cambios
            sudo systemctl restart nginx